### ISSUE TITLE
Data structure - Potential Method

### ISSUE THREAD

**Issue by PotatoesMakeChips** [cjtheham/dx-logger#1]
- one API endpoint to add a contact to the log
- this endpoint checks against grid location and operator callsign and station callsign to auto-sort the entry into the correct log (think sorting for LOTW)

Difference between operator callsign and station:
- operator callsign is the one on your FCC licence
- station callsign is the one you say over the air (think club calls etc)

Potential Issues:
-  uploaded to LOTW/QRZ flags. Maybe a document that contains the IDs of contacts that haven't been uploaded? Having this flag within each logbook would mean scrapping the entire database to upload to lotw (+ others) and that would be slow

**Comment by cjtheham** [comment]
> one API endpoint to add a contact to the log

this is definitely what i was shooting for, as evidenced by the MASSIVE log schema lmao. one post request should enter a log, that will work perfectly.

> this endpoint checks against grid location and operator callsign and station callsign to auto-sort the entry into the correct log (think sorting for LOTW)

i like the thought of doing this mid upload, but i would also say from a logical perspective i don't know if i want to throw an error if grid location and such don't match. might be better off saving it, flagging it somehow as a potentially errored log, and notifying the user for the sake of not losing any data.

> Difference between operator callsign and station: operator callsign is the one on your FCC licence station callsign is the one you say over the air (think club calls etc)

i was mostly making a distinction in the schema for multi-op contest ops potentially, but this is the sort of point i was going for outside of remote ops. for remote ops, i was thinking operator call is the one you say over the air aka your license or club call, and station callsign is the owner of the station. not quite sure how to make that distinction just yet....

> uploaded to LOTW/QRZ flags. Maybe a document that contains the IDs of contacts that haven't been uploaded? Having this flag within each logbook would mean scrapping the entire database to upload to lotw (+ others) and that would be slow

with the current way we are able to grab from the API, we should just be able to implement a query that does findAll(where: qslSentLOTW == false | null), but there are probably better ways to do this. you're completely right, the second a user's db gets probably even just 1k+ contacts uploading and downloading has the chance of becoming painfully slow.

**Comment by PotatoesMakeChips** [comment]
> i was thinking operator call is the one you say over the air aka your license or club call, and station callsign is the owner of the station. not quite sure how to make that distinction

Maybe another database attribute? Kinda like how the RHR log does it. Or we could do something like this:
![image](https://user-images.githubusercontent.com/29355368/161106219-a7c722fc-f365-4694-b6ff-5ba1122513b5.png)
That would allow all the callsigns to change without breaking everything (vanity calls etc). Club call is optional in the log in this model.

> the second a user's db gets probably even just 1k+ contacts uploading and downloading has the chance of becoming painfully slow

TBF that's the only way I can think of doing it what I mentioned adds a load of unnecessary confusion from a database design perspective. In a worst-case scenario, going by some of my logs, we're only looking at 700-900 kilobytes per thousand contacts. 

The only way I can think of doing it in a separate table is like this:
![image](https://user-images.githubusercontent.com/29355368/161100856-386a95ea-72da-4a4b-a8ec-edd55e89c228.png)
and technically that data shouldn't be in another entity as each ID cant be both uploaded to LOTW and not uploaded at the same time. If I'm honest, after modelling it, I think it's a non-issue

**Comment by cjtheham** [comment]
Yeah the more I look at it the more I like your way of doing things. Thinking I agree...let's make club, station, and op calls separate fields. LOTW uploads we can worry about once the time comes but honestly, I don't even think it'll be a pain if we uploaded a million QSOs. Just let it run as a background task, LOTW can handle the pain on their end lmao.

**Comment by PotatoesMakeChips** [comment]
Anything missing from the final structure?
![image](https://user-images.githubusercontent.com/29355368/162420186-e5f4a081-db2f-4115-9597-6a49bbf95b31.png)

*have since added username attribute to User document*

**Comment by cjtheham** [comment]
Other than the weird spelling of *satellite* looks good to me 😂 

I keep getting swamped with some other projects that are just now getting worked on and require my help, but I'll try and find some time this week to work more on the front-end and maybe a little bit on helping you with the back-end (maybe working on finally getting auth0 users working).

**Comment by PotatoesMakeChips** [comment]
![image](https://user-images.githubusercontent.com/29355368/168421369-6d561cb2-3183-4dac-b60c-d02961cedf02.png)
